sudo: false
before_script:
  - npm install -g grunt-cli
language: node_js

node_js:
  - "stable"
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - npm install -g standard

after_script:
  - npm run coveralls
